#!/usr/bin/env python
# coding: utf-8

# In[ ]:


# -*- coding: utf-8 -*-
"""python menu to run various commands..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ku0_WvhFvh-SSxKY2hu6nf3i5hfSfPd2
"""

import os
import webbrowser
import datetime

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def open_website():
    url = input("Enter the website URL: ")
    webbrowser.open(url)

def show_date_time():
    now = datetime.datetime.now()
    print(f"Current Date and Time: {now}")

def create_text_file():
    file_name = input("Enter the file name: ")
    with open(file_name, 'w') as file:
        print("File created successfully!")

def quit_program():
    print("Exiting the program...")
    exit()

def show_menu():
    clear_screen()
    print("===== Python Menu =====")
    print("1. Open a website")
    print("2. Show date and time")
    print("3. Create a new text file")
    print("4. Quit")
    print("=======================")

def run_menu():
    while True:
        show_menu()
        choice = input("Enter your choice (1/2/3/4): ")

        if choice == "1":
            open_website()
        elif choice == "2":
            show_date_time()
        elif choice == "3":
            create_text_file()
        elif choice == "4":
            quit_program()
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    run_menu()


# In[ ]:




